name: Secret Check
on:

  workflow_dispatch:
   
  push:
      paths:
        - .github/workflows/secret_check.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret presence
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID set? ${[[x -z \"$COUDFOREACOUNT_ID\" ]] && echo no || echo yes }"
          echo "CLOUDFORE_API_TOKEN set? ${[[x -z \"$COUDFOREAPI_TOKEN\" ]] && echo no || echo yes }"
          echo "WRANGLER_TOML_CONTENT set? {[[ -z \"$WRANGLER_TOML_CONTENT\" ]] && echo no || echo yes }"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFORE_API_TOKEN: ${{ secrets.CLOUDFOREAPI_TOKEN }}
          WRANGLER_TOML_CONTENT: ${{ secrets.WRANGLER_TOML_CONTENT }}
